version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: gastroflow-mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: GastroFlowMongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
